### ISSUE TITLE
workshop folders need to include a file with link to the lesson repo called lesson.md

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/workshop-metadata#3]

**Comment by mkuzak** [comment]
I have two suggestions to consider.
1. If this information will be read automatically, I suggest a data format, CSV, JSON or yml instead of text format, markdown. 
2. The alternative to one file per lesson, would be a single file at the root of this repository that lists all the URLs of lessons included in the `workshop-metadata` repository.

**Comment by SarahAlidoost** [comment]
@mkuzak please see the pull request https://github.com/esciencecenter-digital-skills/workshop-metadata/pull/13

**Comment by mkuzak** [comment]
I think that is resolved by #13  and can be closed after 13 is merged
