### ISSUE TITLE
add a template for cancellation

### ISSUE THREAD

**Issue by CunliangGeng** [esciencecenter-digital-skills/workshop-metadata#73]
There is no guideline on the workshop website (so also in the metadata) what participants must do when they cannot attend the workshop. Even though there is contact info, there is no requirements for participants to email us to cancel their registration if they cannot attend the workshop at all.

It will be great to make the cancellation requirement explicit and clear. If agreed, we should add one more metadata template for it.

**Comment by Sachavb** [comment]
Hi Cunliang,

In the first and reminder email that we send to the participants we have included below sentence:


If you won’t be able to attend, please cancel your registration (by following instructions here<applewebdata://995B1EF7-554C-4F9F-84E6-87ECC72BFF9F/%5D%20https:/www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration> [3]) so that we can offer your seat to someone on the waiting list.



Best,

Sacha


From: Cunliang Geng ***@***.***>
Date: Monday, 6 February 2023 at 16:00
To: esciencecenter-digital-skills/workshop-metadata ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [esciencecenter-digital-skills/workshop-metadata] add a template for cancellation (Issue #73)

There is no guideline on the workshop website (so also in the metadata) what participants must do when they cannot attend the workshop. Even though there is contact info, there is no requirements for participants to email us to cancel their registration if they cannot attend the workshop at all.

It will be great to make the cancellation requirement explicit and clear. If agreed, we should add one more metadata template for it.

**Comment by CunliangGeng** [comment]
Aha! Thanks for the info.  Would it be also great to add these info to the workshop website?

**Comment by Sachavb** [comment]
Hi Cunliang,

To make the cancellation requirement explicit and clear, could you please add a metadata template for it? 

If you won’t be able to attend, please cancel your registration (by following instructions [here](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration) [4]) so that we can offer your seat to someone on the waiting list.

**Comment by CunliangGeng** [comment]
Thanks for the update. I'm closing the issue then.
